# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{
  stdenv,
  buildGoPackage,
  fetchgit,
  fetchhg,
  fetchbzr,
  fetchsvn,
}:
buildGoPackage rec {
  name = "steamgrid-unstable-${version}";
  version = "2023-04-20";
  rev = "cd672e44ab11284202d1d66fba0bcb1b6589078b";

  goPackagePath = "github.com/boppreh/steamgrid";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/boppreh/steamgrid";
    sha256 = "1xldiln6mh2rzlak9xdfhq05h58wg3h3bys7n728p3x9ymd9xw4r";
  };

  goDeps = ./deps.nix;
  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
