# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/kettek/apng";
    fetch = {
      type = "git";
      url = "https://github.com/kettek/apng";
      rev = "ff692776a607e601f414391b609726401b3b949a";
      sha256 = "0cmvd9m9fs94sv00432ydyphiw8vm90g8vp1p6ln9cn96d05rv2n";
    };
  }
  {
    goPackagePath = "go.deanishe.net/fuzzy";
    fetch = {
      type = "git";
      url = "https://github.com/deanishe/go-fuzzy";
      rev = "74cc511e89801d37b19273a8075b57e86d3ca9c0";
      sha256 = "0gqli9z2r8qjyihz58qgl5mg9s0rd8xz5xsj6mrgspy86vbzmagn";
    };
  }
  {
    goPackagePath = "golang.org/x/image";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/image";
      rev = "9e190ae4a3c5edc736fd99ba38be1c9d08ea5320";
      sha256 = "0l216m0pxxqqjwrc0ki6h4wjnxf898f12q9f6sckcckvb06w2nzi";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "6c97a165dd661335ff7bce6104a008558123c353";
      sha256 = "10mgwlhhyqrxmbrznsx1fdnk43fkn2mbjbcmwkhv0aps74l1xzkl";
    };
  }
]
